FROM almalinux:8
ADD hello.txt /tmp/
#COPY & ADD have same functionality but ADD can do 2 more things.
# 1.It can get content from internet directly and copy
ADD https://raw.githubusercontent.com/DeviSohit/dockerfiles/master/commands.MD /tmp/
# 2.It can directly unzip the files to the specified location
ADD sample-1.tar /tmp/
